import type { Locale } from './config';

export type CorePageSlug = 'database' | 'tools' | 'guide';
type CorePage = {
  title: string; description: string; eyebrow: string; heading: string; introduction: string;
  sectionTitle: string; sectionBody: string; note: string;
  cards: Array<{ name: string; description: string; href: string }>;
};

const links = {
  database: ['/database/weapons/', '/database/vehicles/', '/database/maps/'],
  tools: ['/tools/loadout-builder/', '/tools/weapon-compare/', '/tools/vehicle-compare/'],
  guide: ['/how-to-play/', '/money/', '/map/control-zone/'],
};
const cards = (names: string[], descriptions: string[], hrefs: string[]) => names.map((name, index) => ({ name, description: descriptions[index], href: hrefs[index] }));

export const corePages: Record<Locale, Record<CorePageSlug, CorePage>> = {
  en: {
    database: { title:'WARDOGS Database — Weapons, Vehicles and Maps', description:'Explore the English WARDOGS database for connected weapon, vehicle and map records.', eyebrow:'GAME KNOWLEDGE DATABASE', heading:'WARDOGS Database', introduction:'Use the structured database to move from a broad collection to an individual entity and its related guides, systems and patch history.', sectionTitle:'Connected, version-bound game knowledge', sectionBody:'Records separate confirmed information from unsupported assumptions. Relationships make it easier to follow an entity into comparisons, battlefield systems and practical guidance without losing its patch context.', note:'Detailed entity records are maintained in English while the multilingual knowledge layer expands.', cards:cards(['Weapons database','Vehicles database','Maps database'],['Weapon roles, observed parameters and related loadout guidance.','Transport, aircraft and armored vehicle reference entries.','Terrain identity, orientation and related objective systems.'],links.database) },
    tools: { title:'WARDOGS Tools — Loadout and Entity Comparison', description:'Use WARDOGS tools for loadout planning and weapon or vehicle comparison.', eyebrow:'INTERACTIVE KNOWLEDGE TOOLS', heading:'WARDOGS Tools', introduction:'Choose a planning or comparison tool, then follow its links to the underlying Wiki records for evidence and version context.', sectionTitle:'Tools that preserve source context', sectionBody:'The tools organize decisions without inventing hidden statistics. Unknown values remain unconfirmed, and every useful result should lead back to a database entry or guide.', note:'Interactive tool interfaces currently use English labels.', cards:cards(['Loadout Builder','Weapon Compare','Vehicle Compare'],['Plan a role-focused kit.','Compare weapon references side by side.','Compare battlefield roles across vehicles.'],links.tools) },
    guide: { title:'WARDOGS Guides — Beginner and Battlefield Systems', description:'Start with WARDOGS beginner guides covering match flow, economy and objectives.', eyebrow:'PRACTICAL GUIDES', heading:'WARDOGS Guides', introduction:'Learn the match from its core loop outward: movement, objectives, money, loadouts, construction and team coordination.', sectionTitle:'Start with the system behind the decision', sectionBody:'Guides connect practical advice to the database and clearly mark facts that depend on the current patch. Begin with match basics, then explore economy and Control Zone strategy.', note:'Detailed guides are maintained in English while translations expand.', cards:cards(['How to Play','Money and economy','Control Zone'],['Learn match flow and essential first-battle tactics.','Understand earning, spending and persistent cash.','Review capture rules, scoring and objective control.'],links.guide) },
  },
  'zh-cn': {
    database: { title:'WARDOGS 数据库：武器、载具与地图资料', description:'浏览 WARDOGS 中文数据库入口，查询武器、载具、地图及其关联资料。', eyebrow:'游戏知识数据库', heading:'WARDOGS 数据库', introduction:'通过结构化数据库，从资料集合进入单个实体，并继续查看相关指南、系统与版本记录。', sectionTitle:'有关联且标注版本的游戏知识', sectionBody:'资料会区分已确认信息与缺乏依据的推测。实体关系可将武器、载具或地图连接到比较工具、战场系统和实用指南，同时保留版本背景。', note:'多语言知识层正在扩展，详细实体资料目前以英文维护。', cards:cards(['武器数据库','载具数据库','地图数据库'],['查看武器定位、已观察参数与相关配装指南。','查询运输、航空和装甲载具资料。','了解地图特征、方位与相关目标系统。'],links.database) },
    tools: { title:'WARDOGS 工具：配装规划与实体比较', description:'使用 WARDOGS 工具规划配装，并比较武器或载具的战术定位。', eyebrow:'互动知识工具', heading:'WARDOGS 工具', introduction:'选择规划或比较工具，再通过关联链接查看底层 Wiki 资料、证据与版本背景。', sectionTitle:'保留资料来源背景的工具', sectionBody:'工具用于整理选择，不会虚构隐藏数值。未知数据会保持“尚未确认”，有价值的结果都应能够返回数据库或指南核查。', note:'互动工具的详细操作界面目前使用英文标签。', cards:cards(['配装生成器','武器比较','载具比较'],['规划符合角色需求的装备组合。','并排比较两项武器资料。','比较不同载具的战场定位。'],links.tools) },
    guide: { title:'WARDOGS 指南：新手入门与战场系统', description:'从 WARDOGS 中文指南入口了解对局流程、经济系统与目标玩法。', eyebrow:'实用指南', heading:'WARDOGS 指南', introduction:'从核心对局循环开始，逐步了解移动、目标、经济、配装、建造与团队协作。', sectionTitle:'先理解系统，再作出战术选择', sectionBody:'指南会把实战建议连接到数据库，并明确标注受当前补丁影响的事实。建议先阅读基础玩法，再了解经济与控制区策略。', note:'多语言内容正在扩展，详细指南目前以英文维护。', cards:cards(['如何游玩','金钱与经济','控制区'],['学习对局流程与首场战斗的必要战术。','了解赚钱、消费与持久化现金系统。','查看占领规则、计分与目标控制方式。'],links.guide) },
  },
  es: {
    database: { title:'Base de datos de WARDOGS: armas, vehículos y mapas', description:'Explora en español los registros conectados de armas, vehículos y mapas de WARDOGS.', eyebrow:'BASE DE CONOCIMIENTOS', heading:'Base de datos de WARDOGS', introduction:'Pasa de una colección general a cada entidad y consulta sus guías, sistemas relacionados e historial de versiones.', sectionTitle:'Conocimiento conectado y vinculado a cada versión', sectionBody:'Los registros separan los datos confirmados de las suposiciones. Las relaciones conectan cada entidad con comparaciones, sistemas de batalla y guías prácticas sin perder el contexto del parche.', note:'Los registros detallados se mantienen en inglés mientras crece la capa multilingüe.', cards:cards(['Base de armas','Base de vehículos','Base de mapas'],['Funciones, parámetros observados y guías de equipamiento.','Referencias de transporte, aeronaves y blindados.','Identidad del terreno y sistemas de objetivos relacionados.'],links.database) },
    tools: { title:'Herramientas de WARDOGS: equipamientos y comparaciones', description:'Planifica equipamientos y compara armas o vehículos con las herramientas de WARDOGS.', eyebrow:'HERRAMIENTAS INTERACTIVAS', heading:'Herramientas de WARDOGS', introduction:'Elige una herramienta y sigue sus enlaces hasta los registros Wiki que aportan contexto y evidencia.', sectionTitle:'Decisiones con contexto de fuentes', sectionBody:'Las herramientas organizan decisiones sin inventar estadísticas ocultas. Los valores desconocidos siguen sin confirmar y los resultados enlazan con la base de datos o las guías.', note:'Las interfaces interactivas detalladas usan actualmente etiquetas en inglés.', cards:cards(['Creador de equipamiento','Comparar armas','Comparar vehículos'],['Planifica un equipo centrado en tu función.','Compara dos armas en paralelo.','Compara las funciones de distintos vehículos.'],links.tools) },
    guide: { title:'Guías de WARDOGS: iniciación y sistemas de batalla', description:'Aprende el flujo de partida, la economía y los objetivos con las guías de WARDOGS.', eyebrow:'GUÍAS PRÁCTICAS', heading:'Guías de WARDOGS', introduction:'Aprende primero el ciclo principal y continúa con movimiento, objetivos, dinero, equipamiento, construcción y coordinación.', sectionTitle:'Comprende el sistema antes de decidir', sectionBody:'Las guías conectan consejos prácticos con la base de datos e indican los datos dependientes del parche. Empieza por las reglas básicas y continúa con economía y Control Zone.', note:'Las guías detalladas se mantienen en inglés mientras avanzan las traducciones.', cards:cards(['Cómo jugar','Dinero y economía','Control Zone'],['Aprende el flujo de partida y tácticas esenciales.','Comprende ingresos, gastos y dinero persistente.','Revisa captura, puntuación y control de objetivos.'],links.guide) },
  },
  'pt-br': {
    database: { title:'Banco de dados WARDOGS: armas, veículos e mapas', description:'Explore em português registros conectados de armas, veículos e mapas de WARDOGS.', eyebrow:'BASE DE CONHECIMENTO', heading:'Banco de dados WARDOGS', introduction:'Passe de uma coleção geral para cada entidade e encontre guias, sistemas relacionados e histórico de versões.', sectionTitle:'Conhecimento conectado e vinculado à versão', sectionBody:'Os registros separam informações confirmadas de suposições. As relações conectam entidades a comparações, sistemas de batalha e guias práticos sem perder o contexto do patch.', note:'Os registros detalhados são mantidos em inglês enquanto a camada multilíngue cresce.', cards:cards(['Banco de armas','Banco de veículos','Banco de mapas'],['Funções, parâmetros observados e guias de equipamento.','Referências de transporte, aeronaves e blindados.','Identidade do terreno e sistemas de objetivo relacionados.'],links.database) },
    tools: { title:'Ferramentas WARDOGS: equipamentos e comparações', description:'Planeje equipamentos e compare armas ou veículos com as ferramentas WARDOGS.', eyebrow:'FERRAMENTAS INTERATIVAS', heading:'Ferramentas WARDOGS', introduction:'Escolha uma ferramenta e siga os links até os registros Wiki que fornecem contexto e evidências.', sectionTitle:'Decisões com contexto de fontes', sectionBody:'As ferramentas organizam decisões sem inventar estatísticas ocultas. Valores desconhecidos continuam não confirmados, e os resultados levam ao banco de dados ou aos guias.', note:'As interfaces interativas detalhadas usam atualmente rótulos em inglês.', cards:cards(['Criador de equipamento','Comparar armas','Comparar veículos'],['Planeje um kit voltado para sua função.','Compare duas armas lado a lado.','Compare as funções de diferentes veículos.'],links.tools) },
    guide: { title:'Guias WARDOGS: iniciantes e sistemas de batalha', description:'Aprenda fluxo de partida, economia e objetivos com os guias WARDOGS.', eyebrow:'GUIAS PRÁTICOS', heading:'Guias WARDOGS', introduction:'Aprenda o ciclo principal e avance por movimento, objetivos, dinheiro, equipamentos, construção e coordenação.', sectionTitle:'Entenda o sistema antes de decidir', sectionBody:'Os guias conectam conselhos práticos ao banco de dados e identificam fatos dependentes do patch. Comece pelas regras básicas e continue com economia e Control Zone.', note:'Os guias detalhados são mantidos em inglês enquanto as traduções avançam.', cards:cards(['Como jogar','Dinheiro e economia','Control Zone'],['Aprenda o fluxo da partida e táticas essenciais.','Entenda ganhos, gastos e dinheiro persistente.','Revise captura, pontuação e controle de objetivos.'],links.guide) },
  },
  de: {
    database: { title:'WARDOGS-Datenbank: Waffen, Fahrzeuge und Karten', description:'Durchsuche verbundene WARDOGS-Einträge zu Waffen, Fahrzeugen und Karten auf Deutsch.', eyebrow:'SPIELWISSENSDATENBANK', heading:'WARDOGS-Datenbank', introduction:'Wechsle von einer Sammlung zu einzelnen Entitäten und ihren Guides, Systembezügen und Versionsverläufen.', sectionTitle:'Verknüpftes und versionsgebundenes Wissen', sectionBody:'Einträge trennen bestätigte Informationen von Annahmen. Beziehungen verbinden Entitäten mit Vergleichen, Schlachtfeldsystemen und praktischen Guides, ohne den Patch-Kontext zu verlieren.', note:'Detaillierte Einträge werden auf Englisch gepflegt, während die mehrsprachige Ebene wächst.', cards:cards(['Waffendatenbank','Fahrzeugdatenbank','Kartendatenbank'],['Rollen, beobachtete Parameter und Ausrüstungs-Guides.','Referenzen für Transport-, Luft- und Panzerfahrzeuge.','Geländemerkmale und zugehörige Zielsysteme.'],links.database) },
    tools: { title:'WARDOGS-Werkzeuge: Ausrüstung und Vergleiche', description:'Plane Ausrüstungen und vergleiche Waffen oder Fahrzeuge mit WARDOGS-Werkzeugen.', eyebrow:'INTERAKTIVE WERKZEUGE', heading:'WARDOGS-Werkzeuge', introduction:'Wähle ein Werkzeug und folge den Links zu den Wiki-Einträgen mit Belegen und Versionskontext.', sectionTitle:'Entscheidungen mit Quellenkontext', sectionBody:'Die Werkzeuge ordnen Entscheidungen, ohne verborgene Werte zu erfinden. Unbekannte Daten bleiben unbestätigt, und Ergebnisse führen zurück zur Datenbank oder zu Guides.', note:'Die detaillierten Werkzeugoberflächen verwenden derzeit englische Bezeichnungen.', cards:cards(['Ausrüstungsplaner','Waffen vergleichen','Fahrzeuge vergleichen'],['Plane eine rollenbezogene Ausrüstung.','Vergleiche zwei Waffen direkt.','Vergleiche die Schlachtfeldrollen von Fahrzeugen.'],links.tools) },
    guide: { title:'WARDOGS-Guides: Einstieg und Schlachtfeldsysteme', description:'Lerne Spielablauf, Wirtschaft und Ziele mit den WARDOGS-Guides.', eyebrow:'PRAKTISCHE GUIDES', heading:'WARDOGS-Guides', introduction:'Beginne mit dem Kernablauf und lerne Bewegung, Ziele, Geld, Ausrüstung, Bau und Teamkoordination.', sectionTitle:'Verstehe das System vor der Entscheidung', sectionBody:'Guides verbinden praktische Hinweise mit der Datenbank und kennzeichnen patchabhängige Fakten. Beginne mit den Grundlagen und fahre mit Wirtschaft und Control Zone fort.', note:'Detaillierte Guides werden auf Englisch gepflegt, während Übersetzungen erweitert werden.', cards:cards(['Spielanleitung','Geld und Wirtschaft','Control Zone'],['Lerne Ablauf und wichtige Taktiken für erste Gefechte.','Verstehe Einnahmen, Ausgaben und dauerhaftes Geld.','Prüfe Eroberung, Wertung und Zielkontrolle.'],links.guide) },
  },
  fr: {
    database: { title:'Base de données WARDOGS : armes, véhicules et cartes', description:'Explorez en français les fiches liées des armes, véhicules et cartes de WARDOGS.', eyebrow:'BASE DE CONNAISSANCES', heading:'Base de données WARDOGS', introduction:'Passez d’une collection à chaque entité et consultez ses guides, systèmes associés et historique de versions.', sectionTitle:'Des connaissances liées à chaque version', sectionBody:'Les fiches distinguent les informations confirmées des hypothèses. Les relations relient les entités aux comparaisons, systèmes de bataille et guides sans perdre le contexte du patch.', note:'Les fiches détaillées restent en anglais pendant le développement de la couche multilingue.', cards:cards(['Base des armes','Base des véhicules','Base des cartes'],['Rôles, paramètres observés et guides d’équipement.','Références des transports, aéronefs et blindés.','Identité du terrain et systèmes d’objectifs associés.'],links.database) },
    tools: { title:'Outils WARDOGS : équipements et comparaisons', description:'Préparez vos équipements et comparez armes ou véhicules avec les outils WARDOGS.', eyebrow:'OUTILS INTERACTIFS', heading:'Outils WARDOGS', introduction:'Choisissez un outil puis suivez ses liens vers les fiches Wiki qui apportent preuves et contexte de version.', sectionTitle:'Des décisions qui conservent le contexte', sectionBody:'Les outils organisent les choix sans inventer de statistiques cachées. Les valeurs inconnues restent non confirmées et les résultats renvoient vers la base ou les guides.', note:'Les interfaces détaillées des outils utilisent actuellement des libellés anglais.', cards:cards(['Créateur d’équipement','Comparer les armes','Comparer les véhicules'],['Préparez un équipement adapté à votre rôle.','Comparez deux armes côte à côte.','Comparez les rôles des différents véhicules.'],links.tools) },
    guide: { title:'Guides WARDOGS : débutants et systèmes de bataille', description:'Découvrez le déroulement, l’économie et les objectifs avec les guides WARDOGS.', eyebrow:'GUIDES PRATIQUES', heading:'Guides WARDOGS', introduction:'Apprenez la boucle principale puis le mouvement, les objectifs, l’argent, l’équipement, la construction et la coordination.', sectionTitle:'Comprendre le système avant de choisir', sectionBody:'Les guides relient les conseils pratiques à la base de données et signalent les faits dépendants du patch. Commencez par les bases, puis l’économie et Control Zone.', note:'Les guides détaillés restent en anglais pendant le développement des traductions.', cards:cards(['Comment jouer','Argent et économie','Control Zone'],['Apprenez le déroulement et les tactiques essentielles.','Comprenez les revenus, dépenses et fonds persistants.','Étudiez la capture, le score et le contrôle des objectifs.'],links.guide) },
  },
  ja: {
    database: { title:'WARDOGS データベース：武器・車両・マップ', description:'WARDOGS の武器、車両、マップに関する関連データを日本語で確認できます。', eyebrow:'ゲーム知識データベース', heading:'WARDOGS データベース', introduction:'コレクションから個別エンティティへ進み、関連ガイド、システム、パッチ履歴を確認できます。', sectionTitle:'バージョンに基づく関連知識', sectionBody:'確認済み情報と根拠のない推測を分けて掲載します。関係データから比較、戦場システム、実用ガイドへ移動しても、パッチの背景を確認できます。', note:'多言語レイヤーを拡張中のため、詳細なエンティティ情報は現在英語で管理されています。', cards:cards(['武器データベース','車両データベース','マップデータベース'],['役割、確認済みパラメータ、装備ガイド。','輸送、航空、装甲車両の参照情報。','地形の特徴と関連する目標システム。'],links.database) },
    tools: { title:'WARDOGS ツール：装備構成と比較', description:'WARDOGS ツールで装備を計画し、武器や車両を比較できます。', eyebrow:'インタラクティブツール', heading:'WARDOGS ツール', introduction:'目的に合うツールを選び、リンク先の Wiki データで根拠とバージョン情報を確認してください。', sectionTitle:'情報源の背景を保つツール', sectionBody:'ツールは判断を整理しますが、非公開の数値を推測しません。不明な値は未確認のままとし、結果からデータベースやガイドへ戻れます。', note:'詳細なツール画面は現在英語表記です。', cards:cards(['装備ビルダー','武器比較','車両比較'],['役割に合う装備を計画します。','2つの武器情報を並べて比較します。','車両ごとの戦場での役割を比較します。'],links.tools) },
    guide: { title:'WARDOGS ガイド：初心者向け戦場システム', description:'WARDOGS の試合進行、経済、目標システムを日本語入口から学べます。', eyebrow:'実用ガイド', heading:'WARDOGS ガイド', introduction:'基本ループから始め、移動、目標、資金、装備、建築、チーム連携へ進みます。', sectionTitle:'判断する前にシステムを理解する', sectionBody:'ガイドは実用的な助言をデータベースと結び、パッチに依存する情報を明示します。基本ルールの後に経済と Control Zone を確認してください。', note:'翻訳を拡張中のため、詳細ガイドは現在英語で管理されています。', cards:cards(['遊び方','資金と経済','Control Zone'],['試合の流れと最初に必要な戦術を学びます。','収入、支出、持続する資金を理解します。','占領、得点、目標の制御を確認します。'],links.guide) },
  },
  ko: {
    database: { title:'WARDOGS 데이터베이스: 무기, 차량 및 지도', description:'WARDOGS 무기, 차량, 지도의 연결된 자료를 한국어로 살펴보세요.', eyebrow:'게임 지식 데이터베이스', heading:'WARDOGS 데이터베이스', introduction:'컬렉션에서 개별 엔티티로 이동하고 관련 가이드, 시스템 및 패치 기록을 확인할 수 있습니다.', sectionTitle:'버전에 연결된 지식', sectionBody:'확인된 정보와 근거 없는 추측을 구분합니다. 관계 데이터를 통해 비교, 전장 시스템 및 실전 가이드로 이동하면서도 패치 맥락을 유지할 수 있습니다.', note:'다국어 계층을 확장하는 동안 상세 엔티티 자료는 영어로 관리됩니다.', cards:cards(['무기 데이터베이스','차량 데이터베이스','지도 데이터베이스'],['역할, 관찰된 수치 및 관련 장비 가이드.','수송, 항공 및 장갑 차량 참고 자료.','지형 특징과 관련 목표 시스템.'],links.database) },
    tools: { title:'WARDOGS 도구: 장비 구성 및 비교', description:'WARDOGS 도구로 장비를 계획하고 무기 또는 차량을 비교하세요.', eyebrow:'대화형 지식 도구', heading:'WARDOGS 도구', introduction:'목적에 맞는 도구를 선택한 뒤 연결된 Wiki 자료에서 근거와 버전 정보를 확인하세요.', sectionTitle:'출처 맥락을 유지하는 도구', sectionBody:'도구는 결정을 정리하지만 숨겨진 수치를 만들어내지 않습니다. 알 수 없는 값은 미확인 상태로 두며 결과에서 데이터베이스나 가이드로 돌아갈 수 있습니다.', note:'상세 도구 화면은 현재 영어 레이블을 사용합니다.', cards:cards(['장비 구성 도구','무기 비교','차량 비교'],['역할에 맞는 장비를 계획합니다.','두 무기 자료를 나란히 비교합니다.','차량의 전장 역할을 비교합니다.'],links.tools) },
    guide: { title:'WARDOGS 가이드: 초보자 및 전장 시스템', description:'WARDOGS 경기 흐름, 경제 및 목표 시스템을 한국어 입구에서 알아보세요.', eyebrow:'실전 가이드', heading:'WARDOGS 가이드', introduction:'핵심 경기 흐름부터 이동, 목표, 자금, 장비, 건설 및 팀 협동까지 단계적으로 알아봅니다.', sectionTitle:'결정하기 전에 시스템 이해하기', sectionBody:'가이드는 실전 조언을 데이터베이스와 연결하고 패치에 따라 달라지는 정보를 표시합니다. 기본 규칙부터 시작해 경제와 Control Zone 전략으로 이어가세요.', note:'번역을 확장하는 동안 상세 가이드는 영어로 관리됩니다.', cards:cards(['게임 방법','자금과 경제','Control Zone'],['경기 흐름과 첫 전투에 필요한 전술을 배웁니다.','수입, 지출 및 지속 자금을 이해합니다.','점령, 점수 및 목표 통제를 확인합니다.'],links.guide) },
  },
};
