import type { Locale } from './config';

export type EntityCollectionSlug = 'weapons' | 'vehicles' | 'items' | 'maps';
type CollectionCopy = { title: string; description: string; eyebrow: string; heading: string; intro: string; contextTitle: string; context: string };
type EntityCollectionMessages = {
  labels: { name: string; type: string; status: string; open: string };
  verifiedNote: string;
  collections: Record<EntityCollectionSlug, CollectionCopy>;
};

export const entityCollectionMessages: Record<Locale, EntityCollectionMessages> = {
  en: { labels:{name:'Name',type:'Type',status:'Status',open:'Open record'}, verifiedNote:'Records remain version-bound. Unsupported values are marked as currently unconfirmed.', collections:{
    weapons:{title:'WARDOGS Weapons Database — English',description:'Browse WARDOGS weapon records by name and battlefield role.',eyebrow:'DATABASE / WEAPONS',heading:'Weapons Database',intro:'Open a weapon record for its role, observed parameters and links to related loadout guidance.',contextTitle:'How to read weapon records',context:'Weapon choice depends on role, engagement distance, budget and the complete loadout. The database avoids unsupported precision.'},
    vehicles:{title:'WARDOGS Vehicles Database — English',description:'Browse WARDOGS transport, aircraft and armored vehicle records.',eyebrow:'DATABASE / VEHICLES',heading:'Vehicles Database',intro:'Compare vehicle records by battlefield purpose and continue to logistics, crew and role guidance.',contextTitle:'Vehicle context matters',context:'Mobility, crew requirements and intended battlefield work matter more than a name alone. Check the linked guide before spending persistent cash.'},
    items:{title:'WARDOGS Items Database',description:'Browse WARDOGS equipment, attachment, ammunition and loadout data categories.',eyebrow:'DATABASE / ITEMS',heading:'Items Database',intro:'Use the item model index to understand supported equipment categories without treating schema examples as live game facts.',contextTitle:'Confirmed data only',context:'Armor, attachments, ammunition and loadouts are modeled separately so future records can preserve compatibility and version relationships.'},
    maps:{title:'WARDOGS Maps Database — English',description:'Browse WARDOGS map records and terrain orientation references.',eyebrow:'DATABASE / MAPS',heading:'Maps Database',intro:'Open a named map record for terrain identity, orientation anchors and related objective systems.',contextTitle:'Terrain is not the objective',context:'Named maps describe the wider battlefield. The randomized Control Zone is layered onto that terrain during a live match.'},
  }},
  'zh-cn': { labels:{name:'名称',type:'类型',status:'状态',open:'打开资料'}, verifiedNote:'所有资料均对应特定版本；缺乏可靠依据的数值会标记为“尚未确认”。', collections:{
    weapons:{title:'WARDOGS 武器数据库',description:'按名称与战场定位浏览 WARDOGS 武器资料。',eyebrow:'数据库 / 武器',heading:'武器数据库',intro:'打开武器资料，查看战术定位、已观察参数及相关配装指南。',contextTitle:'如何阅读武器资料',context:'武器选择取决于角色、交战距离、预算与完整配装。数据库不会用推测填补精确数值。'},
    vehicles:{title:'WARDOGS 载具数据库',description:'浏览 WARDOGS 运输、航空与装甲载具资料。',eyebrow:'数据库 / 载具',heading:'载具数据库',intro:'根据战场用途比较载具，并继续查看后勤、乘员和角色指南。',contextTitle:'载具需要结合使用场景',context:'机动性、乘员需求和预期任务比名称本身更重要。花费持久化资金前应查看关联指南。'},
    items:{title:'WARDOGS 物品数据库',description:'浏览 WARDOGS 装备、配件、弹药和配装数据类型。',eyebrow:'数据库 / 物品',heading:'物品数据库',intro:'物品模型索引用于说明已支持的数据类型，不会把 schema 示例冒充实际游戏资料。',contextTitle:'只收录可确认的数据',context:'护甲、配件、弹药与配装分别建模，以便未来资料保留兼容关系和版本记录。'},
    maps:{title:'WARDOGS 地图数据库',description:'浏览 WARDOGS 地图资料与地形方位参考。',eyebrow:'数据库 / 地图',heading:'地图数据库',intro:'打开地图资料，查看地形特征、方位参照与相关目标系统。',contextTitle:'地形不等于目标区域',context:'命名地图描述完整战场；随机控制区会在实时对局中叠加到该地形上。'},
  }},
  es: { labels:{name:'Nombre',type:'Tipo',status:'Estado',open:'Abrir ficha'}, verifiedNote:'Los datos dependen de la versión. Los valores sin respaldo se marcan como no confirmados.', collections:{
    weapons:{title:'Base de armas de WARDOGS',description:'Consulta armas de WARDOGS por nombre y función táctica.',eyebrow:'BASE / ARMAS',heading:'Base de armas',intro:'Abre una ficha para revisar su función, parámetros observados y guías de equipamiento.',contextTitle:'Cómo leer las fichas de armas',context:'La elección depende de la función, distancia, presupuesto y equipo completo. La base evita cifras sin respaldo.'},
    vehicles:{title:'Base de vehículos de WARDOGS',description:'Consulta transportes, aeronaves y blindados de WARDOGS.',eyebrow:'BASE / VEHÍCULOS',heading:'Base de vehículos',intro:'Compara vehículos por su propósito y continúa hacia guías de logística, tripulación y función.',contextTitle:'El contexto del vehículo importa',context:'La movilidad, la tripulación y la tarea prevista importan más que el nombre. Revisa las guías antes de gastar dinero persistente.'},
    items:{title:'Base de objetos de WARDOGS',description:'Consulta categorías de equipo, accesorios, munición y equipamientos.',eyebrow:'BASE / OBJETOS',heading:'Base de objetos',intro:'El índice muestra los tipos de datos admitidos sin presentar ejemplos de esquema como hechos del juego.',contextTitle:'Solo datos confirmados',context:'Armadura, accesorios, munición y equipamientos se modelan por separado para conservar compatibilidad y versiones.'},
    maps:{title:'Base de mapas de WARDOGS',description:'Consulta mapas de WARDOGS y referencias de orientación.',eyebrow:'BASE / MAPAS',heading:'Base de mapas',intro:'Abre un mapa para revisar terreno, puntos de orientación y sistemas de objetivos relacionados.',contextTitle:'El terreno no es el objetivo',context:'Los mapas describen el campo de batalla; la Control Zone aleatoria se sitúa sobre ese terreno en cada partida.'},
  }},
  'pt-br': { labels:{name:'Nome',type:'Tipo',status:'Status',open:'Abrir registro'}, verifiedNote:'Os registros dependem da versão. Valores sem suporte são marcados como não confirmados.', collections:{
    weapons:{title:'Banco de armas WARDOGS',description:'Consulte armas de WARDOGS por nome e função de combate.',eyebrow:'BANCO / ARMAS',heading:'Banco de armas',intro:'Abra um registro para ver função, parâmetros observados e guias de equipamento.',contextTitle:'Como ler registros de armas',context:'A escolha depende de função, distância, orçamento e equipamento completo. O banco evita precisão sem suporte.'},
    vehicles:{title:'Banco de veículos WARDOGS',description:'Consulte transportes, aeronaves e blindados de WARDOGS.',eyebrow:'BANCO / VEÍCULOS',heading:'Banco de veículos',intro:'Compare veículos pelo propósito e continue para guias de logística, tripulação e função.',contextTitle:'O contexto do veículo importa',context:'Mobilidade, tripulação e tarefa planejada importam mais que o nome. Consulte os guias antes de gastar dinheiro persistente.'},
    items:{title:'Banco de itens WARDOGS',description:'Consulte categorias de equipamento, acessórios, munição e loadouts.',eyebrow:'BANCO / ITENS',heading:'Banco de itens',intro:'O índice mostra tipos de dados suportados sem apresentar exemplos de schema como fatos do jogo.',contextTitle:'Somente dados confirmados',context:'Armadura, acessórios, munição e loadouts são modelados separadamente para preservar compatibilidade e versões.'},
    maps:{title:'Banco de mapas WARDOGS',description:'Consulte mapas WARDOGS e referências de orientação.',eyebrow:'BANCO / MAPAS',heading:'Banco de mapas',intro:'Abra um mapa para revisar terreno, pontos de orientação e sistemas de objetivo relacionados.',contextTitle:'O terreno não é o objetivo',context:'Mapas descrevem o campo de batalha; a Control Zone aleatória é posicionada sobre esse terreno em cada partida.'},
  }},
  de: { labels:{name:'Name',type:'Typ',status:'Status',open:'Eintrag öffnen'}, verifiedNote:'Einträge sind versionsgebunden. Nicht belegte Werte bleiben unbestätigt.', collections:{
    weapons:{title:'WARDOGS-Waffendatenbank',description:'Durchsuche WARDOGS-Waffen nach Name und Schlachtfeldrolle.',eyebrow:'DATENBANK / WAFFEN',heading:'Waffendatenbank',intro:'Öffne einen Eintrag für Rolle, beobachtete Parameter und passende Ausrüstungs-Guides.',contextTitle:'Waffeneinträge richtig lesen',context:'Die Wahl hängt von Rolle, Entfernung, Budget und kompletter Ausrüstung ab. Unbelegte Präzision wird vermieden.'},
    vehicles:{title:'WARDOGS-Fahrzeugdatenbank',description:'Durchsuche Transport-, Luft- und Panzerfahrzeuge in WARDOGS.',eyebrow:'DATENBANK / FAHRZEUGE',heading:'Fahrzeugdatenbank',intro:'Vergleiche Fahrzeuge nach Zweck und öffne Guides zu Logistik, Besatzung und Rolle.',contextTitle:'Fahrzeugkontext ist entscheidend',context:'Mobilität, Besatzung und Aufgabe sind wichtiger als der Name. Prüfe Guides, bevor du dauerhaftes Geld ausgibst.'},
    items:{title:'WARDOGS-Gegenstandsdatenbank',description:'Durchsuche Datenkategorien für Ausrüstung, Aufsätze, Munition und Loadouts.',eyebrow:'DATENBANK / GEGENSTÄNDE',heading:'Gegenstandsdatenbank',intro:'Der Modellindex zeigt unterstützte Datentypen, ohne Schema-Beispiele als Spielfakten auszugeben.',contextTitle:'Nur bestätigte Daten',context:'Rüstung, Aufsätze, Munition und Loadouts werden getrennt modelliert, um Kompatibilität und Versionen zu erhalten.'},
    maps:{title:'WARDOGS-Kartendatenbank',description:'Durchsuche WARDOGS-Karten und Orientierungshilfen.',eyebrow:'DATENBANK / KARTEN',heading:'Kartendatenbank',intro:'Öffne eine Karte für Geländeidentität, Orientierungspunkte und verbundene Zielsysteme.',contextTitle:'Gelände ist nicht das Zielgebiet',context:'Karten beschreiben das Schlachtfeld; die zufällige Control Zone wird im laufenden Match darauf platziert.'},
  }},
  fr: { labels:{name:'Nom',type:'Type',status:'Statut',open:'Ouvrir la fiche'}, verifiedNote:'Les fiches dépendent de la version. Les valeurs non étayées restent non confirmées.', collections:{
    weapons:{title:'Base des armes WARDOGS',description:'Parcourez les armes WARDOGS par nom et rôle tactique.',eyebrow:'BASE / ARMES',heading:'Base des armes',intro:'Ouvrez une fiche pour consulter son rôle, ses paramètres observés et les guides d’équipement.',contextTitle:'Lire une fiche d’arme',context:'Le choix dépend du rôle, de la distance, du budget et de l’équipement complet. La base évite toute précision non étayée.'},
    vehicles:{title:'Base des véhicules WARDOGS',description:'Parcourez transports, aéronefs et blindés de WARDOGS.',eyebrow:'BASE / VÉHICULES',heading:'Base des véhicules',intro:'Comparez les véhicules par fonction puis consultez les guides de logistique, d’équipage et de rôle.',contextTitle:'Le contexte du véhicule compte',context:'Mobilité, équipage et mission comptent davantage que le nom. Consultez les guides avant de dépenser des fonds persistants.'},
    items:{title:'Base des objets WARDOGS',description:'Parcourez les catégories d’équipement, accessoires, munitions et configurations.',eyebrow:'BASE / OBJETS',heading:'Base des objets',intro:'L’index présente les types pris en charge sans faire passer les exemples de schéma pour des faits du jeu.',contextTitle:'Données confirmées uniquement',context:'Armures, accessoires, munitions et configurations sont modélisés séparément pour préserver compatibilité et versions.'},
    maps:{title:'Base des cartes WARDOGS',description:'Parcourez les cartes WARDOGS et leurs repères d’orientation.',eyebrow:'BASE / CARTES',heading:'Base des cartes',intro:'Ouvrez une carte pour consulter le terrain, les repères et les systèmes d’objectifs associés.',contextTitle:'Le terrain n’est pas l’objectif',context:'Les cartes décrivent le champ de bataille ; la Control Zone aléatoire est placée sur ce terrain pendant la partie.'},
  }},
  ja: { labels:{name:'名称',type:'種類',status:'状態',open:'詳細を開く'}, verifiedNote:'情報はバージョンに基づきます。根拠のない数値は未確認として扱います。', collections:{
    weapons:{title:'WARDOGS 武器データベース',description:'WARDOGS の武器を名称と戦場での役割から確認できます。',eyebrow:'データベース / 武器',heading:'武器データベース',intro:'武器の役割、確認済みパラメータ、関連する装備ガイドを参照できます。',contextTitle:'武器データの読み方',context:'選択には役割、距離、予算、装備全体が関係します。根拠のない精密な数値は掲載しません。'},
    vehicles:{title:'WARDOGS 車両データベース',description:'WARDOGS の輸送、航空、装甲車両を確認できます。',eyebrow:'データベース / 車両',heading:'車両データベース',intro:'目的別に車両を比較し、兵站、乗員、役割のガイドへ移動できます。',contextTitle:'車両は用途が重要',context:'機動性、必要な乗員、任務は名称以上に重要です。資金を使う前に関連ガイドを確認してください。'},
    items:{title:'WARDOGS アイテムデータベース',description:'装備、アタッチメント、弾薬、ロードアウトのデータ種類を確認できます。',eyebrow:'データベース / アイテム',heading:'アイテムデータベース',intro:'スキーマ例を実際のゲーム情報として扱わず、対応するデータ種類を示します。',contextTitle:'確認済みデータのみ',context:'防具、アタッチメント、弾薬、ロードアウトを分けて管理し、互換性とバージョン関係を保持します。'},
    maps:{title:'WARDOGS マップデータベース',description:'WARDOGS のマップと地形の位置関係を確認できます。',eyebrow:'データベース / マップ',heading:'マップデータベース',intro:'地形の特徴、目印、関連する目標システムをマップごとに確認できます。',contextTitle:'地形と目標地点は別です',context:'マップは戦場全体を示し、ランダムな Control Zone は試合中にその地形上へ配置されます。'},
  }},
  ko: { labels:{name:'이름',type:'유형',status:'상태',open:'자료 열기'}, verifiedNote:'자료는 버전에 따라 달라집니다. 근거 없는 수치는 미확인으로 표시합니다.', collections:{
    weapons:{title:'WARDOGS 무기 데이터베이스',description:'WARDOGS 무기를 이름과 전장 역할별로 살펴보세요.',eyebrow:'데이터베이스 / 무기',heading:'무기 데이터베이스',intro:'무기 역할, 관찰된 수치 및 관련 장비 가이드를 확인할 수 있습니다.',contextTitle:'무기 자료 읽는 방법',context:'무기 선택에는 역할, 교전 거리, 예산 및 전체 장비가 영향을 줍니다. 근거 없는 정밀 수치는 제공하지 않습니다.'},
    vehicles:{title:'WARDOGS 차량 데이터베이스',description:'WARDOGS 수송, 항공 및 장갑 차량 자료를 살펴보세요.',eyebrow:'데이터베이스 / 차량',heading:'차량 데이터베이스',intro:'전장 목적에 따라 차량을 비교하고 물류, 승무원 및 역할 가이드로 이동하세요.',contextTitle:'차량은 사용 맥락이 중요합니다',context:'기동성, 승무원 요구 사항과 임무는 이름보다 중요합니다. 지속 자금을 사용하기 전에 관련 가이드를 확인하세요.'},
    items:{title:'WARDOGS 아이템 데이터베이스',description:'장비, 부착물, 탄약 및 장비 구성 데이터 유형을 살펴보세요.',eyebrow:'데이터베이스 / 아이템',heading:'아이템 데이터베이스',intro:'스키마 예시를 실제 게임 정보로 오인하지 않도록 지원되는 데이터 유형만 안내합니다.',contextTitle:'확인된 데이터만 사용',context:'방어구, 부착물, 탄약 및 장비 구성을 별도로 모델링하여 호환성과 버전 관계를 유지합니다.'},
    maps:{title:'WARDOGS 지도 데이터베이스',description:'WARDOGS 지도 자료와 지형 방향 정보를 살펴보세요.',eyebrow:'데이터베이스 / 지도',heading:'지도 데이터베이스',intro:'지도별 지형 특징, 방향 기준점 및 관련 목표 시스템을 확인할 수 있습니다.',contextTitle:'지형과 목표 지역은 다릅니다',context:'지도는 전체 전장을 설명하며 무작위 Control Zone은 실시간 경기에서 그 지형 위에 배치됩니다.'},
  }},
};

export const itemCategoryLinks = [
  { name:'Armor', type:'armor', href:'/equipment/' },
  { name:'Attachments', type:'attachment', href:'/weapons/builds/' },
  { name:'Ammunition', type:'ammunition', href:'/weapons/' },
  { name:'Loadouts', type:'loadout', href:'/loadouts/' },
];
