import type { Locale } from './config';

export const localizedGuideRoutes = [
  'how-to-play','building/fob','map/control-zone','map/drills','map/towers',
  'loadouts/budget','loadouts/medic','loadouts/best-loadouts','loadouts/pilot','loadouts/save-rebuy',
  'money/how-to-make-money','money/logistics','money/persistence','money/pilot',
  'troubleshooting/map-loading-crash','vehicles/air','vehicles/ground','weapons/best-weapons','weapons/builds',
] as const;
export type LocalizedGuideRoute = (typeof localizedGuideRoutes)[number];

const englishTitles = ['How to Play WARDOGS','FOB Building Guide','Control Zone Guide','Drills Guide','Towers Guide','Budget Loadouts','Medic Loadout','Best Loadouts','Pilot Loadout','Save and Rebuy Loadouts','How to Make Money','Logistics Guide','Persistent Money Guide','Pilot Money Guide','Map Loading Crash Fix','Air Vehicles Guide','Ground Vehicles Guide','Best Weapons Guide','Weapon Builds Guide'];
const titleSets: Record<Locale, string[]> = {
  en: englishTitles,
  'zh-cn':['WARDOGS 新手玩法','FOB 建造指南','控制区指南','钻井指南','塔楼指南','低预算配装','医疗兵配装','最佳配装指南','飞行员配装','保存与重新购买配装','如何赚钱','后勤指南','持久化金钱指南','飞行员赚钱指南','地图加载崩溃排查','空中载具指南','地面载具指南','最佳武器指南','武器配置指南'],
  es:['Cómo jugar a WARDOGS','Guía de construcción de FOB','Guía de Control Zone','Guía de perforadoras','Guía de torres','Equipamientos económicos','Equipamiento de médico','Mejores equipamientos','Equipamiento de piloto','Guardar y recomprar equipamientos','Cómo ganar dinero','Guía de logística','Guía de dinero persistente','Guía de ingresos para pilotos','Solución de fallos al cargar mapas','Guía de vehículos aéreos','Guía de vehículos terrestres','Guía de mejores armas','Guía de configuraciones de armas'],
  'pt-br':['Como jogar WARDOGS','Guia de construção de FOB','Guia da Control Zone','Guia de perfuradoras','Guia de torres','Equipamentos econômicos','Equipamento de médico','Melhores equipamentos','Equipamento de piloto','Salvar e recomprar equipamentos','Como ganhar dinheiro','Guia de logística','Guia de dinheiro persistente','Guia de renda para pilotos','Correção de falha ao carregar mapas','Guia de veículos aéreos','Guia de veículos terrestres','Guia das melhores armas','Guia de configurações de armas'],
  de:['WARDOGS spielen','FOB-Bau-Guide','Control-Zone-Guide','Bohranlagen-Guide','Türme-Guide','Günstige Ausrüstungen','Sanitäter-Ausrüstung','Beste Ausrüstungen','Piloten-Ausrüstung','Ausrüstung speichern und erneut kaufen','Geld verdienen','Logistik-Guide','Guide für dauerhaftes Geld','Geld-Guide für Piloten','Absturz beim Laden der Karte beheben','Luftfahrzeug-Guide','Bodenfahrzeug-Guide','Guide für die besten Waffen','Waffenbau-Guide'],
  fr:['Comment jouer à WARDOGS','Guide de construction des FOB','Guide de la Control Zone','Guide des foreuses','Guide des tours','Équipements économiques','Équipement du médecin','Meilleurs équipements','Équipement du pilote','Sauvegarder et racheter un équipement','Comment gagner de l’argent','Guide de logistique','Guide de l’argent persistant','Guide de revenus du pilote','Corriger le plantage au chargement des cartes','Guide des véhicules aériens','Guide des véhicules terrestres','Guide des meilleures armes','Guide des configurations d’armes'],
  ja:['WARDOGS の遊び方','FOB 建築ガイド','Control Zone ガイド','ドリルガイド','タワーガイド','低予算ロードアウト','メディック用ロードアウト','おすすめロードアウト','パイロット用ロードアウト','ロードアウトの保存と再購入','資金の稼ぎ方','兵站ガイド','持続資金ガイド','パイロット向け資金ガイド','マップ読み込みクラッシュの対処','航空車両ガイド','地上車両ガイド','おすすめ武器ガイド','武器ビルドガイド'],
  ko:['WARDOGS 플레이 방법','FOB 건설 가이드','Control Zone 가이드','드릴 가이드','타워 가이드','저예산 장비 구성','메딕 장비 구성','추천 장비 구성','파일럿 장비 구성','장비 저장 및 재구매','자금 버는 방법','물류 가이드','지속 자금 가이드','파일럿 수익 가이드','지도 로딩 충돌 해결','항공 차량 가이드','지상 차량 가이드','추천 무기 가이드','무기 빌드 가이드'],
};

type GuideUi = { eyebrow:string; titleSuffix:string; description:string; intro:string; understand:string; understandBody:string; apply:string; applyBody:string; verify:string; verifyBody:string; related:string; hub:string; source:string };
export const guideUi: Record<Locale, GuideUi> = {
  en:{eyebrow:'WARDOGS GUIDE',titleSuffix:'WARDOGS Guide',description:'Localized WARDOGS guide for {title}, with practical context and version-aware source links.',intro:'This localized guide introduces {title} and connects the topic to the current WARDOGS knowledge base.',understand:'Understand the system',understandBody:'Start with the purpose of the system and the decision it supports. Match conditions, team needs and available resources can change the correct choice.',apply:'Use it in a match',applyBody:'Apply the guidance as a sequence: confirm the objective, review your role and budget, then choose the action that supports the team. Recheck assumptions when the battlefield changes.',verify:'Version and evidence',verifyBody:'Balance, prices and mechanics can change between patches. Unsupported precision is not presented as fact; use the full source guide for detailed, version-bound evidence.',related:'Related guidance',hub:'Open localized guide hub',source:'Open full source guide'},
  'zh-cn':{eyebrow:'WARDOGS 指南',titleSuffix:'WARDOGS 中文指南',description:'{title} 的 WARDOGS 本地化指南，包含实战背景与版本资料链接。',intro:'本地化指南介绍“{title}”，并将主题连接到当前 WARDOGS 知识库。',understand:'理解系统',understandBody:'先确认系统的用途以及它要帮助解决的决策。对局状况、团队需求和可用资源都会改变最佳选择。',apply:'在对局中应用',applyBody:'按顺序使用指南：确认目标，检查角色和预算，再选择能够支持团队的行动。战场变化后应重新核对原有判断。',verify:'版本与证据',verifyBody:'平衡、价格和机制可能随补丁变化。缺乏依据的精确数值不会作为事实展示；详细的版本证据请查看完整原始指南。',related:'相关指南',hub:'打开本地化指南中心',source:'打开完整原始指南'},
  es:{eyebrow:'GUÍA DE WARDOGS',titleSuffix:'Guía de WARDOGS',description:'Guía localizada sobre {title}, con contexto práctico y fuentes vinculadas a la versión.',intro:'Esta guía presenta {title} y conecta el tema con la base de conocimientos actual de WARDOGS.',understand:'Comprender el sistema',understandBody:'Empieza por la finalidad del sistema y la decisión que permite tomar. La partida, el equipo y los recursos disponibles pueden cambiar la mejor opción.',apply:'Aplicarlo en una partida',applyBody:'Confirma el objetivo, revisa tu función y presupuesto y elige una acción que ayude al equipo. Revisa tus supuestos cuando cambie el campo de batalla.',verify:'Versión y evidencia',verifyBody:'El equilibrio, los precios y las mecánicas cambian entre parches. La precisión sin respaldo no se presenta como hecho; consulta la guía completa para ver la evidencia.',related:'Guías relacionadas',hub:'Abrir portal de guías',source:'Abrir guía completa'},
  'pt-br':{eyebrow:'GUIA WARDOGS',titleSuffix:'Guia WARDOGS',description:'Guia localizado sobre {title}, com contexto prático e fontes vinculadas à versão.',intro:'Este guia apresenta {title} e conecta o tema à base de conhecimento atual de WARDOGS.',understand:'Entenda o sistema',understandBody:'Comece pela finalidade do sistema e pela decisão que ele ajuda a tomar. A partida, a equipe e os recursos disponíveis podem mudar a melhor escolha.',apply:'Use em uma partida',applyBody:'Confirme o objetivo, revise função e orçamento e escolha uma ação que ajude a equipe. Reavalie as premissas quando o campo de batalha mudar.',verify:'Versão e evidência',verifyBody:'Balanceamento, preços e mecânicas mudam entre patches. Precisão sem suporte não é apresentada como fato; consulte o guia completo para ver as evidências.',related:'Guias relacionados',hub:'Abrir portal de guias',source:'Abrir guia completo'},
  de:{eyebrow:'WARDOGS-GUIDE',titleSuffix:'WARDOGS-Guide',description:'Lokalisierter Guide zu {title} mit praktischem Kontext und versionsgebundenen Quellen.',intro:'Dieser Guide führt in {title} ein und verbindet das Thema mit der aktuellen WARDOGS-Wissensdatenbank.',understand:'Das System verstehen',understandBody:'Beginne mit dem Zweck des Systems und der unterstützten Entscheidung. Match, Team und verfügbare Ressourcen können die richtige Wahl verändern.',apply:'Im Match anwenden',applyBody:'Bestätige das Ziel, prüfe Rolle und Budget und wähle eine teamdienliche Aktion. Bewerte Annahmen neu, wenn sich das Schlachtfeld ändert.',verify:'Version und Belege',verifyBody:'Balance, Preise und Mechaniken können sich ändern. Unbelegte Präzision wird nicht als Fakt dargestellt; der vollständige Guide enthält versionsgebundene Belege.',related:'Verwandte Guides',hub:'Lokalisiertes Guide-Portal öffnen',source:'Vollständigen Guide öffnen'},
  fr:{eyebrow:'GUIDE WARDOGS',titleSuffix:'Guide WARDOGS',description:'Guide localisé sur {title}, avec contexte pratique et sources liées à la version.',intro:'Ce guide présente {title} et relie le sujet à la base de connaissances WARDOGS actuelle.',understand:'Comprendre le système',understandBody:'Commencez par le but du système et la décision qu’il facilite. La partie, l’équipe et les ressources disponibles peuvent modifier le meilleur choix.',apply:'Appliquer en partie',applyBody:'Confirmez l’objectif, vérifiez votre rôle et votre budget, puis choisissez une action utile à l’équipe. Réévaluez vos hypothèses si le champ de bataille change.',verify:'Version et preuves',verifyBody:'L’équilibrage, les prix et les mécaniques peuvent changer. Aucune précision non étayée n’est présentée comme un fait ; consultez le guide complet pour les preuves.',related:'Guides associés',hub:'Ouvrir le portail des guides',source:'Ouvrir le guide complet'},
  ja:{eyebrow:'WARDOGS ガイド',titleSuffix:'WARDOGS 日本語ガイド',description:'{title} のローカライズガイドです。実戦の背景とバージョン情報へのリンクを掲載します。',intro:'このガイドでは「{title}」を紹介し、現在の WARDOGS 知識データベースへ接続します。',understand:'システムを理解する',understandBody:'まずシステムの目的と、判断を助ける内容を確認します。試合状況、チームの需要、利用可能な資源によって適切な選択は変わります。',apply:'試合で活用する',applyBody:'目標を確認し、役割と予算を見直して、チームに役立つ行動を選びます。戦況が変化したら前提を再確認してください。',verify:'バージョンと根拠',verifyBody:'バランス、価格、仕組みはパッチで変わる場合があります。根拠のない精密値は事実として扱わず、詳細は完全な原文ガイドで確認できます。',related:'関連ガイド',hub:'ローカライズガイド一覧',source:'完全な原文ガイドを開く'},
  ko:{eyebrow:'WARDOGS 가이드',titleSuffix:'WARDOGS 한국어 가이드',description:'{title} 현지화 가이드로 실전 맥락과 버전별 출처 링크를 제공합니다.',intro:'이 가이드는 {title} 주제를 소개하고 현재 WARDOGS 지식 데이터베이스와 연결합니다.',understand:'시스템 이해하기',understandBody:'먼저 시스템의 목적과 지원하는 결정을 확인하세요. 경기 상황, 팀 요구 사항과 사용 가능한 자원에 따라 올바른 선택이 달라질 수 있습니다.',apply:'경기에서 활용하기',applyBody:'목표를 확인하고 역할과 예산을 검토한 뒤 팀에 도움이 되는 행동을 선택하세요. 전장이 바뀌면 기존 판단을 다시 확인해야 합니다.',verify:'버전과 근거',verifyBody:'밸런스, 가격과 메커니즘은 패치에 따라 달라질 수 있습니다. 근거 없는 정밀 수치는 사실로 제시하지 않으며 자세한 증거는 전체 원문 가이드에서 확인합니다.',related:'관련 가이드',hub:'현지화 가이드 허브 열기',source:'전체 원문 가이드 열기'},
};

export const guideTitles = Object.fromEntries(Object.entries(titleSets).map(([locale,titles]) => [locale,Object.fromEntries(localizedGuideRoutes.map((route,index) => [route,titles[index]]))])) as Record<Locale, Record<LocalizedGuideRoute,string>>;
export const guideSourceUrl = (route: LocalizedGuideRoute) => route === 'how-to-play' ? '/how-to-play/' : `/${route}/`;
export const fillGuideText = (text:string,title:string) => text.replaceAll('{title}', title);
export const relatedGuideRoutes = (route: LocalizedGuideRoute): LocalizedGuideRoute[] => {
  const index = localizedGuideRoutes.indexOf(route);
  const previous = localizedGuideRoutes[(index - 1 + localizedGuideRoutes.length) % localizedGuideRoutes.length];
  const next = localizedGuideRoutes[(index + 1) % localizedGuideRoutes.length];
  return [previous, next];
};

export type GuideCategory = 'beginner'|'construction'|'objective'|'loadout'|'economy'|'troubleshooting'|'vehicle'|'weapon';
export const guideCategory = (route: LocalizedGuideRoute): GuideCategory => route === 'how-to-play' ? 'beginner' : route.startsWith('building/') ? 'construction' : route.startsWith('map/') ? 'objective' : route.startsWith('loadouts/') ? 'loadout' : route.startsWith('money/') ? 'economy' : route.startsWith('troubleshooting/') ? 'troubleshooting' : route.startsWith('vehicles/') ? 'vehicle' : 'weapon';
type GuideEnhancement = { sourceSummary:string; focusTitle:string; focus:Record<GuideCategory,string>; checklistTitle:string; checklist:[string,string,string] };
export const guideEnhancements: Record<Locale,GuideEnhancement> = {
  en:{sourceSummary:'Source guide summary',focusTitle:'What this guide helps you decide',focus:{beginner:'Use this topic to understand the first-match sequence: identify the objective, choose one useful role and learn when to move, fight or resupply.',construction:'Construction guidance is about location, supply flow and team access. A structure is useful only when it supports the frontline without consuming resources blindly.',objective:'Map-system guidance connects terrain awareness to objective timing. Read landmarks, travel routes and team pressure together instead of treating one marker as the whole battle.',loadout:'Loadout guidance balances role, budget, engagement range and utility. The strongest kit is the one that completes a clear task without risking unnecessary persistent cash.',economy:'Economy guidance separates earning opportunities from spending priorities. Consider survival, transport, team support and the next purchase before committing cash.',troubleshooting:'Troubleshooting guidance narrows the failure before changing settings. Reproduce the issue, isolate one variable at a time and preserve working configuration where possible.',vehicle:'Vehicle guidance begins with battlefield purpose, crew needs and route risk. Choose a platform for the task rather than treating every vehicle as interchangeable transport.',weapon:'Weapon guidance compares combat role and realistic use conditions. Range, positioning, ammunition and the rest of the kit matter more than an unsupported ranking.'},checklistTitle:'Practical review checklist',checklist:['Confirm the current objective, role and available resources.','Open the complete source guide and check any patch-sensitive details.','Compare the planned action with at least one safer or cheaper alternative.']},
  'zh-cn':{sourceSummary:'原始指南摘要',focusTitle:'此指南帮助解决什么问题',focus:{beginner:'此主题用于理解首场对局顺序：确认目标，选择一个有用角色，并学习何时移动、交战或补给。',construction:'建造决策取决于位置、补给流和团队通行。只有能够支援前线且不会盲目消耗资源的设施才有价值。',objective:'地图系统指南把地形判断与目标时机连接起来。应综合观察地标、移动路线和团队压力，而不是只盯着一个标记。',loadout:'配装需要平衡角色、预算、交战距离与功能。能够完成明确任务且不会无谓损失持久化资金的组合更实用。',economy:'经济指南区分赚钱机会和消费优先级。花钱前应同时考虑生存、运输、团队支援和下一次购买。',troubleshooting:'故障排查应先缩小问题范围，再修改设置。复现问题，每次只隔离一个变量，并尽量保留原本正常的配置。',vehicle:'载具选择从战场用途、乘员需求和路线风险开始。应为任务选择平台，不要把所有载具都当作可互换的运输工具。',weapon:'武器判断应结合战斗定位和真实使用条件。距离、站位、弹药与完整配装比缺乏依据的排名更重要。'},checklistTitle:'实战检查清单',checklist:['确认当前目标、角色和可用资源。','打开完整原始指南，核对受补丁影响的细节。','将计划行动与至少一个更安全或更便宜的替代方案比较。']},
  es:{sourceSummary:'Resumen de la guía fuente',focusTitle:'Qué decisión ayuda a tomar',focus:{beginner:'Comprende la primera partida: identifica el objetivo, elige una función útil y aprende cuándo moverte, combatir o reabastecerte.',construction:'Construir depende de ubicación, suministros y acceso del equipo. Una estructura sirve si apoya el frente sin gastar recursos a ciegas.',objective:'Relaciona terreno y momento del objetivo. Lee juntos los puntos de referencia, rutas y presión del equipo, no un único marcador.',loadout:'Equilibra función, presupuesto, distancia y utilidad. El mejor equipo completa una tarea clara sin arriesgar dinero persistente sin necesidad.',economy:'Separa oportunidades de ingreso y prioridades de gasto. Considera supervivencia, transporte, apoyo y la siguiente compra antes de pagar.',troubleshooting:'Aísla el fallo antes de cambiar ajustes. Reproduce el problema, modifica una variable cada vez y conserva la configuración que funciona.',vehicle:'Empieza por propósito, tripulación y riesgo de ruta. Elige una plataforma para la tarea; los vehículos no son transportes intercambiables.',weapon:'Compara función y condiciones reales. Distancia, posición, munición y equipo completo importan más que una clasificación sin respaldo.'},checklistTitle:'Lista práctica',checklist:['Confirma objetivo, función y recursos disponibles.','Abre la guía completa y revisa los detalles dependientes del parche.','Compara la acción con una alternativa más segura o económica.']},
  'pt-br':{sourceSummary:'Resumo do guia fonte',focusTitle:'Qual decisão este guia ajuda a tomar',focus:{beginner:'Entenda a primeira partida: identifique o objetivo, escolha uma função útil e aprenda quando mover, lutar ou reabastecer.',construction:'Construção depende de local, fluxo de suprimentos e acesso da equipe. Uma estrutura vale quando apoia a frente sem desperdiçar recursos.',objective:'Conecte leitura do terreno ao tempo do objetivo. Analise marcos, rotas e pressão da equipe em conjunto, não apenas um marcador.',loadout:'Equilibre função, orçamento, distância e utilidade. O melhor kit cumpre uma tarefa clara sem arriscar dinheiro persistente sem necessidade.',economy:'Separe oportunidades de renda e prioridades de gasto. Considere sobrevivência, transporte, suporte e a próxima compra antes de pagar.',troubleshooting:'Isole a falha antes de mudar configurações. Reproduza o problema, altere uma variável por vez e preserve o que funciona.',vehicle:'Comece por propósito, tripulação e risco da rota. Escolha a plataforma para a tarefa; veículos não são transportes intercambiáveis.',weapon:'Compare função e condições reais. Distância, posição, munição e kit completo importam mais que um ranking sem suporte.'},checklistTitle:'Lista prática',checklist:['Confirme objetivo, função e recursos disponíveis.','Abra o guia completo e verifique detalhes sensíveis ao patch.','Compare a ação com uma alternativa mais segura ou econômica.']},
  de:{sourceSummary:'Zusammenfassung des Quell-Guides',focusTitle:'Welche Entscheidung dieser Guide unterstützt',focus:{beginner:'Verstehe den Ablauf des ersten Matches: Ziel erkennen, eine nützliche Rolle wählen und Bewegung, Kampf sowie Nachschub einordnen.',construction:'Bauen hängt von Standort, Nachschub und Teamzugang ab. Eine Struktur ist sinnvoll, wenn sie die Front ohne blinden Ressourcenverbrauch unterstützt.',objective:'Verbinde Gelände mit Zielzeitpunkt. Werte Landmarken, Routen und Teamdruck gemeinsam aus, statt nur einer Markierung zu folgen.',loadout:'Balanciere Rolle, Budget, Entfernung und Nutzen. Die beste Ausrüstung erfüllt eine klare Aufgabe ohne unnötiges dauerhaftes Geld zu riskieren.',economy:'Trenne Einnahmechancen von Ausgabenprioritäten. Berücksichtige Überleben, Transport, Unterstützung und den nächsten Kauf.',troubleshooting:'Grenze den Fehler ein, bevor du Einstellungen änderst. Reproduziere ihn, ändere jeweils eine Variable und bewahre funktionierende Konfigurationen.',vehicle:'Beginne mit Zweck, Besatzung und Routenrisiko. Wähle eine Plattform für die Aufgabe; Fahrzeuge sind nicht beliebig austauschbar.',weapon:'Vergleiche Rolle und reale Bedingungen. Entfernung, Position, Munition und Gesamtausrüstung sind wichtiger als unbelegte Ranglisten.'},checklistTitle:'Praktische Prüfliste',checklist:['Bestätige Ziel, Rolle und verfügbare Ressourcen.','Öffne den vollständigen Guide und prüfe patchabhängige Details.','Vergleiche die Aktion mit einer sichereren oder günstigeren Alternative.']},
  fr:{sourceSummary:'Résumé du guide source',focusTitle:'La décision facilitée par ce guide',focus:{beginner:'Comprenez la première partie : identifiez l’objectif, choisissez un rôle utile et apprenez quand vous déplacer, combattre ou vous ravitailler.',construction:'La construction dépend de l’emplacement, du ravitaillement et de l’accès de l’équipe. Une structure doit soutenir le front sans gaspiller les ressources.',objective:'Reliez le terrain au rythme de l’objectif. Analysez ensemble repères, itinéraires et pression de l’équipe plutôt qu’un seul marqueur.',loadout:'Équilibrez rôle, budget, distance et utilité. Le meilleur équipement accomplit une tâche claire sans risquer inutilement les fonds persistants.',economy:'Distinguez revenus et priorités de dépense. Pensez à la survie, au transport, au soutien et au prochain achat avant de payer.',troubleshooting:'Isolez la panne avant de changer les réglages. Reproduisez le problème, modifiez une variable à la fois et conservez la configuration fonctionnelle.',vehicle:'Commencez par la mission, l’équipage et le risque de l’itinéraire. Choisissez une plateforme adaptée ; les véhicules ne sont pas interchangeables.',weapon:'Comparez rôle et conditions réelles. Distance, position, munitions et équipement complet comptent plus qu’un classement non étayé.'},checklistTitle:'Liste de contrôle pratique',checklist:['Confirmez l’objectif, le rôle et les ressources disponibles.','Ouvrez le guide complet et vérifiez les détails liés au patch.','Comparez l’action à une solution plus sûre ou moins coûteuse.']},
  ja:{sourceSummary:'原文ガイドの概要',focusTitle:'このガイドで判断できること',focus:{beginner:'最初の試合の流れを理解します。目標を確認し、役立つ役割を選び、移動、戦闘、補給のタイミングを学びます。',construction:'建築は場所、補給、チームの利用しやすさで判断します。前線を支援し、資源を無駄にしない施設だけが有効です。',objective:'地形情報と目標のタイミングを結び付けます。ひとつのマーカーだけでなく、目印、移動経路、チームの圧力を合わせて判断します。',loadout:'役割、予算、交戦距離、機能を調整します。明確な仕事を果たし、持続資金を無駄にしない装備が実用的です。',economy:'収入機会と支出の優先順位を分けます。生存、輸送、支援、次の購入を考えてから資金を使います。',troubleshooting:'設定を変える前に原因を絞ります。問題を再現し、一度にひとつの変数を変更して、動作する設定を残します。',vehicle:'戦場での目的、必要な乗員、経路の危険から判断します。すべての車両を同じ輸送手段として扱わず、任務に合うものを選びます。',weapon:'役割と実際の使用条件を比較します。根拠のない順位より、距離、位置、弾薬、装備全体が重要です。'},checklistTitle:'実戦チェックリスト',checklist:['現在の目標、役割、利用可能な資源を確認する。','完全な原文ガイドでパッチ依存の詳細を確認する。','予定した行動を、より安全または安価な代替案と比較する。']},
  ko:{sourceSummary:'원문 가이드 요약',focusTitle:'이 가이드가 지원하는 결정',focus:{beginner:'첫 경기 흐름을 이해하세요. 목표를 확인하고 유용한 역할을 선택한 뒤 이동, 전투 및 보급 시점을 익힙니다.',construction:'건설은 위치, 보급 흐름과 팀 접근성으로 판단합니다. 자원을 낭비하지 않고 전선을 지원하는 구조물만 가치가 있습니다.',objective:'지형 판단과 목표 타이밍을 연결합니다. 하나의 표식만 보지 말고 랜드마크, 이동 경로와 팀 압박을 함께 읽어야 합니다.',loadout:'역할, 예산, 교전 거리와 유틸리티를 균형 있게 구성합니다. 명확한 임무를 수행하며 지속 자금을 불필요하게 위험에 빠뜨리지 않는 구성이 좋습니다.',economy:'수익 기회와 지출 우선순위를 구분합니다. 생존, 수송, 팀 지원과 다음 구매를 고려한 뒤 자금을 사용하세요.',troubleshooting:'설정을 바꾸기 전에 오류 범위를 좁히세요. 문제를 재현하고 한 번에 하나의 변수만 바꾸며 정상 설정을 보존합니다.',vehicle:'전장 목적, 승무원 요구와 경로 위험부터 확인합니다. 모든 차량을 같은 수송 수단으로 보지 말고 임무에 맞는 플랫폼을 선택하세요.',weapon:'전투 역할과 실제 사용 조건을 비교합니다. 근거 없는 순위보다 거리, 위치, 탄약과 전체 장비 구성이 중요합니다.'},checklistTitle:'실전 점검 목록',checklist:['현재 목표, 역할과 사용 가능한 자원을 확인합니다.','전체 원문 가이드에서 패치 관련 세부 정보를 확인합니다.','계획한 행동을 더 안전하거나 저렴한 대안과 비교합니다.']},
};
